# email for sending the finishing and error message
email: tangming2005@gmail.com
from_fastq: True
paired_end: True
# >70bp long, <70bp false
long_reads: True

# what's the control for IP
control: 'Input'

ref_fa: /n/regal/informatics_public/reference_genome_by_tommy/ucsc/mm9/mm9.fa
macs_g: mm
macs_pvalue: 1e-8
macs2_g: mm
macs2_pvalue: 1e-5
macs2_pvalue_broad: 1e-5

#phantompeakqual path
phantom_path: /n/home02/mtang/apps/phantompeakqualtools/run_spp.R
#rose path, only specify the folder
rose_path: /n/home02/mtang/apps/ROSE/young_computation-rose-1a9bb86b5464
rose_g: mm9

## if downsample is false, will only do a symbolic link
downsample: True
#number of reads downsample to, I set to 50 million, if reads number smaller than
## 50 million, downsample will keep the orignal reads
target_reads: 50000000

## run chromHMM or not
chromHMM: False
# the folder, keep the trailing slash
chromHMM_path: /n/home02/mtang/apps/chromHMM/ChromHMM/

##chromHMM bin size
binsize: 200
#chromatin state model
state: 15
##chromHMM genome
chromHmm_g : mm9

## histone marks that you want to include in the chromHMM model
## space delimited. entries should be from the third column of the meta.txt file fed
## into the samples2json.py file.

histone_for_chromHMM: "K4me1 K4me3 K27ac K27me3"

# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES: './SRR.txt'
SAMPLES_JSON: './samples.json'

CLUSTER_JSON: './cluster.json'
